server:
  port: 8080

spring:
  datasource:
    username: root
    password: Sony123Julek!
    url: jdbc:mysql://localhost:3306/user
    driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  show-sql: true
  hibernate:
    ddl-auto: create
    format_sql: true
